spring.application.name=motoMicroservicio

server.port=8003

logging.pattern.dateformat=hh:mm
spring.main.banner-mode=off
spring.thymeleaf.cache=false
#Postgrest conexion
spring.datasource.url=jdbc:mysql://localhost/moto_microservicio
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Mostrar sql en consola
spring.jpa.properties.hibernate.show_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# Configuración para crear/actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
#Para limpiar la BBDD
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
eureka.client.enabled=false

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
